services:
  - type: web
    name: english-practicer-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm run start:prod
    plan: free
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: PORT
        value: "3001"
